from asset import Asset
from vulnerability import Vulnerability

def build_ticket(asset: Asset, vuln: Vulnerability) -> tuple[str, str]:
    title = f"[REMEDIATE NOW] {vuln.cve_id} on {asset.hostname}"

    desc_lines = [
        "## Asset",
        f"- Hostname: {asset.hostname}",
        f"- IP: {asset.ip_address or 'n/a'}",
        f"- OS: {asset.os or 'n/a'}",
        f"- Environment: {asset.environment or 'n/a'}",
        f"- Owner: {asset.owner_context or 'n/a'}",
        f"- Source: {asset.source}",
        "",
        "## Vulnerability",
        f"- CVE: {vuln.cve_id}",
        f"- Title: {vuln.title}",
        f"- CVSS: {vuln.cvss_score if vuln.cvss_score is not None else 'n/a'}",
        f"- Exploit available: {vuln.exploit_available}",
        f"- Status: {vuln.status}",
        "",
        "## Recommended Fix",
        vuln.recommended_fix or "n/a",
        "",
        "## Notes",
        "This ticket was generated by the Ironclad Unified Inventory CLI as a simulation of remediation workflow.",
    ]

    return title, "\n".join(desc_lines)
